#!/usr/bin/env bash

if [ "${ADOMEJI_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
ADOMEJI_CONTEXT_LOADED=1

ADOMEJI_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADOMEJI_PROJECT_ROOT="$(cd "$ADOMEJI_LIB_DIR/../.." && pwd)"

if [ -f "$ADOMEJI_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ADOMEJI_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"

ADOMEJI_BUILD_OUTPUT="${ADOMEJI_BUILD_DIR:-$ADOMEJI_PROJECT_ROOT/build/Adomeji}"
ADOMEJI_BOOTSTRAP_BUILD_OUTPUT="${ADOMEJI_BOOTSTRAP_BUILD_DIR:-$ADOMEJI_PROJECT_ROOT/build/Adomeji.Bootstrap}"
ADOMEJI_UPDATE_ENGINE_BUILD_OUTPUT="${ADOMEJI_UPDATE_ENGINE_BUILD_DIR:-$ADOMEJI_PROJECT_ROOT/build/Adomeji.UpdateEngine}"
ADOMEJI_INSTALL_PATH="${ADOMEJI_INSTALL_DIR:-$ADOFAI_MODS_DIR/Adomeji}"
ADOMEJI_PACKAGE_ROOT="${ADOMEJI_PACKAGE_BUILD_DIR:-$ADOMEJI_PROJECT_ROOT/build/package}"
ADOMEJI_PACKAGE_STAGE="$ADOMEJI_PACKAGE_ROOT/Adomeji"
ADOMEJI_PACKAGE_ZIP_PATH="${ADOMEJI_PACKAGE_ZIP:-$ADOMEJI_PROJECT_ROOT/build/Adomeji.zip}"
ADOMEJI_UPDATE_MANIFEST_PATH="${ADOMEJI_UPDATE_MANIFEST:-$ADOMEJI_PROJECT_ROOT/build/Adomeji.update.json}"
ADOMEJI_VERSION="${ADOMEJI_VERSION:-0.1.0}"

export ADOMEJI_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_EXE UNITY_MOD_MANAGER_DLL
export ADOMEJI_BUILD_OUTPUT ADOMEJI_INSTALL_PATH
export ADOMEJI_BOOTSTRAP_BUILD_OUTPUT ADOMEJI_UPDATE_ENGINE_BUILD_OUTPUT
export ADOMEJI_PACKAGE_ROOT ADOMEJI_PACKAGE_STAGE ADOMEJI_PACKAGE_ZIP_PATH
export ADOMEJI_UPDATE_MANIFEST_PATH ADOMEJI_VERSION
