<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>

    <Nullable>disable</Nullable>

    <AssemblyName>Adomeji</AssemblyName>
    <RootNamespace>Adomeji</RootNamespace>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityModManager">
      <HintPath>$(UnityModManagerDll)</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(AdofaiManaged)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(AdofaiManaged)/Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>$(AdofaiManaged)/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>$(AdofaiManaged)/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="RDTools">
      <HintPath>$(AdofaiManaged)/RDTools.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(AdofaiManaged)/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <PackageReference
      Include="Lib.Harmony.Ref"
      Version="2.3.6"
      PrivateAssets="all"
      ExcludeAssets="runtime"
    />
  </ItemGroup>
</Project>
